### ISSUE TITLE
Pipeline parameters are not reported as span attributes by Elastic APM

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#109]
### Version report

Jenkins and plugins versions report: 
* Jenkins opentelemetry-plugin 0.10-beta
* Elastic Observability 7.12.1

### Reproduction steps

* Create a parameterized pipeline and execute it
* Visualise the trace in Elastic APM, the fields `ci.pipeline.parameter.name`,  `ci.pipeline.parameter.sensitive`, and `ci.pipeline.parameter.value` are not reported by Elastic APM as span attributes when Jaeger reports them.

```groovy
pipeline {
    agent any
    
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage('Example') {
            steps {
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
            }
        }
    }
}
```

### Results

Expected result as visible with Jaeger 1.22:

![image](https://user-images.githubusercontent.com/459691/117791034-34e9e580-b24a-11eb-992e-8d90eeeae70a.png)

Actual result with Elastic APM 7.12.1:

![image](https://user-images.githubusercontent.com/459691/117791164-50ed8700-b24a-11eb-9847-f3312c7643e5.png)

**Comment by cyrille-leclerc** [comment]
Being fixed by https://github.com/elastic/apm-server/pull/5286

**Comment by v1v** [comment]
It works in 7.13.1

![image](https://user-images.githubusercontent.com/2871786/123643437-4730da80-d81c-11eb-9f5c-5f441d6423a3.png)


Pipeline -> https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/master/1054/parameters/
