### ISSUE TITLE
Dynamic service naming to support CI at Scale

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#112]
### Dependencies

NA

### Feature Request

This is related to the discussion done in https://github.com/jenkinsci/opentelemetry-plugin/issues/88

@skundrik proposed another way to configure the service name based on the Jenkins URL. Something like grok to extract parts you want and combine them into service name.

### Context

The current implementation is something that can now be configured with the Jenkins UI (Global settings) and JCasC.

The proposal could allow to provide an opinionated way to configure the service name instead allowing users to set the naming the would like.

### Questions

I'd like to highlight some cases to consider about this approach and what the proposal should do in those cases:

- What if the URL is too long?
- What if the URL contains details that are specific for the deployment type (like the k8s [FQDN](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/))?
- What if the URL has not been configured?

**Comment by kuisathaverat** [comment]
The plugin supports setting the service name, it is a setting you set one time when you configure the plugin, I do not see the need to make it dynamic.
