### ISSUE TITLE
Jenkins admins need dashboards and alerts on the health of the Jenkins platform

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#113]
# Problem Description

Jenkins admins need dashboards and alerts to solve the following problems:
* Overall health indicators of the health of the Jenkins platform
* Detect build agent allocation problems 
* Detect Jenkins controller responsiveness problems
   * Web UI responsiveness
* Detect File System usage problems, GC problems, CPU problems on Jenkins controller...
   * It's not exactly user facing problems but we know these are critical indicators to look at.
   * Ideally we would identify symptoms of these root causes and monitor / alert on the symptoms

**Comment by cyrille-leclerc** [comment]
See https://github.com/jenkinsci/opentelemetry-plugin/pull/114

**Comment by skundrik** [comment]
@cyrille-leclerc I was intrigued by this so I went to try it out but looks like dashboards are saved for Kibana 7.13 which hasn't been released yet so they fail to import. ☹️

**Comment by cyrille-leclerc** [comment]
Sorry to hear this @skundrik , I guess that the cause of this glitch saving as 7.13 is that we are often working with 7.13-SNAPSHOT to get coming improvements on the OTLP support.
@v1v do you think we could make these dashboards compatible with 7.12?  ref https://github.com/jenkinsci/opentelemetry-plugin/pull/114

**Comment by v1v** [comment]
😞 , I didn't even realise I was using the latest candidate snapshot, in fact I though they were version independent, there is nothing specific for that particular version.

I'll raise a new PR with the support for the latest release version

**Comment by v1v** [comment]
https://github.com/jenkinsci/opentelemetry-plugin/pull/116 is the now the one with support for 7.12

**Comment by cyrille-leclerc** [comment]
Closing: solved with
* Elastic / Kibana dashboard: https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/DASHBOARDS.md
* Splunk dashboard: https://github.com/splunk/splunk-jenkins-otel
