### ISSUE TITLE
Add support for detecting Maven build type

### ISSUE THREAD

**Issue by skundrik** [jenkinsci/opentelemetry-plugin#144]
### Feature Request

Looks like the usual suspects like freestyle, pipeline and multi-branch are are correctly detected in the pipeline type but a still fairly common Maven one is missing.

Looks like all that's missing is a bit of code in the **OtelUtils** class to detect the run type as **hudson.maven.AbstractMavenBuild** similar to what is already done for **freestyle** build.

**Comment by cyrille-leclerc** [comment]
Please test new plugin version https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-0.17

**Comment by skundrik** [comment]
Seems to be working fine so far and my unknown jobs are now being marked with maven
