### ISSUE TITLE
Standardising env vars `TRACEPARENT` and `TRACESTATE` in OTel specification

### ISSUE THREAD

**Issue by aidansteele** [jenkinsci/opentelemetry-plugin#156]
I was [told about this project](https://twitter.com/iamvlaaaaaaad/status/1429691926182256642) yesterday and I am very excited by the work you are doing. 

Have you considered "upstreaming" your usage of `TRACEPARENT` and `TRACESTATE` environment variables to the OpenTelemetry specification? I feel that it would be a valuable addition to the spec. There was an issue opened about a year ago regarding env vars as carriers but it hasn't since progressed: https://github.com/open-telemetry/opentelemetry-specification/issues/740.

I feel it would be valuable because there are a few different solutions currently out there and they are generally vendor-specific. E.g.

* Honeycomb.io has a [tool for use in CI that sets a `HONEYCOMB_TRACE`](https://github.com/honeycombio/buildevents#attaching-more-traces-from-your-build-and-test-process) environment variable. 
* BuildKite.com's [agent injects a `BUILDKITE_TRACE_CONTEXT`](https://github.com/buildkite/agent/blob/a635daa4768580af8da8e1f4c6f2926892ec6f2b/tracetools/propagate.go#L14) environment variable with the OpenTracing context. 

Right now there are very few general-purpose tools that emit distributed tracing data and I expect it's because there is no standard. It could be exceedingly useful to have unit test frameworks emit spans for test suites, have infrastructure-as-code tools (e.g. Terraform, CDK) emit spans for resource creation, have integration tests propagate spans to systems under test, etc. And it feels that this plugin's choice of env vars has the best chance of being generally useful and achieving this goal.

What are your thoughts? I imagine that @v1v and/or @cyrille-leclerc both have more experience in the OTel space than I do personally. I would be happy to attempt to submit an OTEP for this idea, but I imagine that either of you might have a better idea of how to do so successfully.

**Comment by cyrille-leclerc** [comment]
You are right @aidansteele that we have enough maturity to propagate the trace context between CI platforms and build tools using `TRACEPARENT` and `TRACESTATE` to propose a standardisation.

**Comment by kuisathaverat** [comment]
The plugin enables propagation of `TRACEPARENT`and `TRACESTATE`, all the matters about OpenTelemetry specification are managed at https://github.com/open-telemetry/opentelemetry-specification/issues/740
