### ISSUE TITLE
Support defining attributes at the job levels that are added to spans

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#173]
### Feature Request

We want pipeline author to be able to specify in their pipeline definition some attributes/properties that are added to all the spans of the pipeline execution.

Will be particularly interesting when producing reports from metrics derived from pipeline executions.

E.g. define in labels the "team name", "business unit name"

### Specification

* Job level attributes will be added to spans using [`io.opentelemetry.api.trace.Span#setAttribute(java.lang.String, java.lang.String)`](https://javadoc.io/static/io.opentelemetry/opentelemetry-api-trace/0.13.1/io/opentelemetry/api/trace/Span.html#setAttribute(java.lang.String,java.lang.String))
* To specify job level attributes, we can either
   * Add specific open telemetry attributes
   * Or use an existing capability of Jenkins to define job level attributes
      * There don't seem to be generic attributes / labels at the job level in Jenkins Core. Are there popular plugins to solve this problem?

**Comment by ipleten** [comment]
Yes it would be great to have, like New Relic Jenkins plugin supports customAttributes on job config level.
It also would be great to allow to set some vars from Jenkins global ENV variables and/or some internal variables/macros if possible (IINM some of them appear only after pipeline was actually started or checkout happened.)

The goal we are trying to achieve is to co-relate Pipeline failures with shared library/plugins/jenkins core versions  as well as some external systems (like our custom deployment engine version, infra terraform code version) even if pipeline wasn't actually start (e.g. syntax error, git server not reachable etc).

So we want to inject shared libraries commit SHA (and potentially some other info via CaSC) to Jenkins (currently via global Jenkins Env.) and see them as a custom metadata in traces. 

Another case is that we have different types of pipelines (we use MPL-based shared library so jenkinsFiles look like: MPLPythonPipeline {...} or MPLNodePipeline{...} ). So we would also set this data in Job attributes to get fancy dashboard per pipelineType not per repo.

**Comment by cyrille-leclerc** [comment]
Thanks for the feedback @ipleten . Can you please share with us few details please:
* Which trace analytics tool do you use?
* Do you expect those attributes to be defined on the top-level span, the pipeline span? Or on sub-spans like a `stage` span?

**Comment by christophe-kamphaus-jemmic** [comment]
Could `WithSpanAttributeStep` be extended to have additional `target` options to set the attributes on all children of the target span as well? Or add a parameter `children` to toggle this behavior on the children of the target span?

**Comment by christophe-kamphaus-jemmic** [comment]
> > Could `WithSpanAttributeStep` be extended to have additional `target` options to set the attributes on all children of the target span as well? Or add a parameter `children` to toggle this behavior on the children of the target span?
> 
> @christophe-kamphaus-jemmic the idea is very interesting. I guess it will require a bit of work. Contributions are welcome.

I'm working on it. I will share a PR soon.

**Comment by christophe-kamphaus-jemmic** [comment]
@cyrille-leclerc Could you review the PR https://github.com/jenkinsci/opentelemetry-plugin/pull/827 ?
