### ISSUE TITLE
Add attributes for build trigger step

### ISSUE THREAD

**Issue by dotstone** [jenkinsci/opentelemetry-plugin#204]
It would be cool to get additional span attributes of the build trigger step. It's defined in the pipeline-build-step-plugin: https://github.com/jenkinsci/pipeline-build-step-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java

Especially interesting would be the fields that describe the triggered job/build:
* job
* parameters
* some information to identify the triggered build. That could be the URL or the build id of the triggered build or even a link to the trace of the triggered build. I don't know where to get that info from though.

My goal is to correlate triggered builds with their parent.

**Comment by v1v** [comment]
Hi @dotstone,

Thanks for reaching out. There is a discussion regarding context propagation between parentstream and downstream jobs in https://github.com/jenkinsci/opentelemetry-plugin/discussions/98

Though, those attributes that you mention can be in any case collected and added to the `build` step span. It should be feasible similar to what we have done for the `git` and `sh`/`bat` steps

Is that something you would like to contribute to?

**Comment by cyrille-leclerc** [comment]
Implementation in progress with 
- https://github.com/jenkinsci/opentelemetry-plugin/pull/208

@dotstone 

> Especially interesting would be the fields that describe the triggered job/build:
> * job

It will be the attribute `ci.pipeline.name=${triggeredJob.name}` on the span `Build: ${triggeredJob.name}`

> * parameters

It will be visible on the downstream span that will be the root span of the triggered job, will it be enough


> * some information to identify the triggered build. That could be the URL or the build id of the triggered build or even a link to the trace of the triggered build. I don't know where to get that info from though.

We are adding on the job root span the multivalued attribute `ci.pipeline.run.cause` with a chain of machine readable causes of an execution like [`UserIdCause:anonymous`] 

@dotstone  would that work for your needs?

**Comment by dotstone** [comment]
Hi @cyrille-leclerc,
thank you for your answer and the link to the discussion - I wasn't aware that this is already being discussed.

> It will be visible on the downstream span that will be the root span of the triggered job, will it be enough? We could add it later on the "Build: xxx" step for analytics purpose.

Yes, that sounds great. I think that covers all of my use cases. Thanks a lot for all the effort! 💯

**Comment by cyrille-leclerc** [comment]
Code merged

**Comment by cyrille-leclerc** [comment]
Please test https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-0.22-beta-3

**Comment by cyrille-leclerc** [comment]
@dotstone can you please bump to v1.0.0 and confirm your problem is solved?

* https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-1.0.0

**Comment by dotstone** [comment]
Thank you. Are you going to update the plugin on plugins.jenkins.io as well? That would make it easier to test for me. Otherwise I can check until the beginning of next week.

**Comment by cyrille-leclerc** [comment]
Thanks @dotstone, the upload of v1.0.0 failed, I have to retry and check.
https://repo.jenkins-ci.org/public/io/jenkins/plugins/opentelemetry/

**Comment by cyrille-leclerc** [comment]
Plugin uploaded manually doing a `mvn deploy` on the source code tag. It's not yet visible in the Jenkins Update Center, I hope it will appear soon.

ref https://repo.jenkins-ci.org/releases/io/jenkins/plugins/opentelemetry/1.0.0/

**Comment by cyrille-leclerc** [comment]
Version 1.0.0 of the Jenkins Otel Plugin is now available in the Jenkins update center. I tested with a Jenkins LTS  (version  2.303.3)

**Comment by dotstone** [comment]
Thanks, I wasn't able to test it with 1.0.0 yet since our jenkins runs into a configuration problem after upgrading - we need to do more investigation on that. I checked with 0.22-beta4 though and the results look very good. The spans are linked and the parameters are visible in the linked span. I also have the information to identify the triggered build (by the URL).
My use cases are covered, thanks again!

I'll check version 1.0.0 as soon as we made progress on our jenkins deployment and will get back to you next week.

**Comment by cyrille-leclerc** [comment]
Please wait, the 1.0.0 build is broken due to a dirty build environment trying to do the `mvn deploy`  https://github.com/jenkinsci/opentelemetry-plugin/issues/230

I'm cutting a 1.0.1

**Comment by cyrille-leclerc** [comment]
Please check v1.0.1 rather than 1.0.0
https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-1.0.1

**Comment by dotstone** [comment]
Verified also with 1.0.1 - thank you!
