### ISSUE TITLE
Record agent/node steps

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#21]
### What

Trace the agent/node steps as spans

### Why

Then we can start answering questions such as:

- How long does it take to provision the node? 
- What's the agent with more calls?

**Comment by v1v** [comment]
My very first attempt with the below pipeline

```
pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    }
}

```


![image](https://user-images.githubusercontent.com/2871786/110832064-ceb90480-8292-11eb-8f94-02851b6e224c.png)

**Comment by cyrille-leclerc** [comment]
@v1v hmm, we are likely to have to track "onAfterStartNode" in addition to the "onBeforeStartXxx" that we do usually  
I have implemented this a while ago and deleted the code to simplify, this piece of code is hard to read :neutral_face:

https://github.com/jenkinsci/opentelemetry-plugin/blob/7d80e48df4e27517a748cd443d32c28431638a48/src/main/java/io/jenkins/plugins/opentelemetry/job/jenkins/GraphListenerAdapterToPipelineListener.java#L29
