### ISSUE TITLE
Elastic Kibana dashboard should be parameterized by `service.name`

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#242]
### Feature Request

Elastic Kibana dashboard should be parameterized by `service.name` so I can narrow down my visualization to the Jenkins controller that matters to me.

This capability should be integrated with:
- https://github.com/jenkinsci/opentelemetry-plugin/issues/238

**Comment by v1v** [comment]
First attempt:
- https://github.com/jenkinsci/opentelemetry-plugin/pull/251
