### ISSUE TITLE
Support for OTLP/HTTP

### ISSUE THREAD

**Issue by dkluba** [jenkinsci/opentelemetry-plugin#247]
### Feature Request

Is there planned support for exporting using OTLP/HTTP aside of OTLP/gRPC? Or is there any blocker for that?

**Comment by cyrille-leclerc** [comment]
Thanks @dkluba for reaching out.
No blocker, it's just that we thought OTLP GRPC was good enough. We probably have to add the OTLP HTTP exporter jar and extend the GUI.

Could you please share with us why you prefer OTLP HTTP rather than OTLP GRPC?

**Comment by cyrille-leclerc** [comment]
Commit https://github.com/jenkinsci/opentelemetry-plugin/pull/271/commits/0096290547c5fdd34bfcc0272a15d41e13a37454 will help deliver OTLP/HTTP

**Comment by cyrille-leclerc** [comment]
Commit https://github.com/jenkinsci/opentelemetry-plugin/pull/271/commits/0096290547c5fdd34bfcc0272a15d41e13a37454 will help deliver OTLP/HTTP

**Comment by cyrille-leclerc** [comment]
@dkluba can you please test https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-1.2.0-rc1 adding the configuration property `otel.exporter.otlp.protocol=http/protobuf'

**Comment by cyrille-leclerc** [comment]
@dkluba please prefer 1.2.0-rc2 : https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-1.2.0-rc2

**Comment by dkluba** [comment]
Thanks! I'll give it a try soon.

Sorry I didn't respond - I asked out of curiosity, following the trend in OT of making HTTP default one (or at least this is my impression)

**Comment by cyrille-leclerc** [comment]
Hello @dkluba  , we run a survey to better understand Jenkins Observability needs and more broadly CI/CD Observability needs, could you by any chance answer it?
https://docs.google.com/forms/d/e/1FAIpQLSezbndR1bpPj4YeWquLLWEYOkEjEI-lSyNbtDUVrR-udpt2lA/viewform?usp=sf_link
