### ISSUE TITLE
'sh' step errors don't provide much insights

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#261]
### Feature Request

Pipeline Shell Step errors are not very meaningful. Could we enable logs correlation ? Or capture stderr?

![image](https://user-images.githubusercontent.com/459691/146547534-7c530ad4-0e8a-4ec5-939b-a6f4a9059d39.png)

cc @kuisathaverat

**Comment by ipleten** [comment]
Yeah it would be extra useful but keep in mind it might expose some sensitive data like tokens or passwords.
In general I have a big hope to use this plugin to quick detect problems with pipelines in big Jenkins setup. 
So we want to get answers for:

- Which stage fails the most of the time
- Which step in stage causes this and why
- Pipeline status (FAILED, UNSTABLE and so on)
- What's shared libraries version is in use
- ...

All these should be labeled with 'project name ' and 'branch' at least. So we could use Kibana to build some queries per project, branch, agent_name and so on.

**Comment by cyrille-leclerc** [comment]
Good catch @ipleten . We could focus on collecting build logs with OpenTelemetry combined with the existing capability of trace exploration products to visualize logs associated with traces. Thanks to this, the security permission mechanisms of the trace explorer handles the problem of sensitive data.

**Comment by dhruvatee** [comment]
Hi @kuisathaverat @cyrille-leclerc , Is there a specific timeline to get this enhancement? This will really helpful for us. Please do share, If there are any quick alternatives that we could do to get this shell failure cause information is available in trace. Thanks in advance!

**Comment by kuisathaverat** [comment]
spans and logs correlation is there the `trace.id` and `spand.id` are the same so showing the context of the error is a task for the backend.
