### ISSUE TITLE
Input Step is not Ignore when added to the Ignore List

### ISSUE THREAD

**Issue by BenB196** [jenkinsci/opentelemetry-plugin#289]
### Jenkins and plugins versions report

Jenkins: 2.327
OS: Linux - 5.4.0-91-generic
---
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
authorize-project:1.4.0
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jira:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:734.v2f848c5e6ea2
cloudbees-folder:6.17
command-launcher:1.6
configuration-as-code:1.55
credentials:1055.v1346ba467ba1
credentials-binding:1.27
display-url-api:2.3.5
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
favorite:2.3.3
font-awesome-api:5.15.4-5
generic-webhook-trigger:1.79
git:4.10.1
git-client:3.10.1
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
gitlab-api:1.0.6
gitlab-branch-source:1.5.9
gitlab-plugin:1.5.26
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.28
jackson2-api:2.13.1-244.v773c36c5b330
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.2
jira:3.6
jira-steps:1.6.0
jjwt-api:0.11.2-9.c8b45b8bb173
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes:1.31.1
kubernetes-client-api:5.10.1-171.vaa0774fb8c20
kubernetes-credentials:0.9.0
lockable-resources:2.13
mailer:1.34
matrix-auth:3.0
matrix-project:1.19
metrics:4.0.2.8
momentjs:1.1.1
multibranch-scan-webhook-trigger:1.0.9
okhttp-api:4.9.3-105.vb96869f8ac3a
opentelemetry:1.0.1
pipeline-build-step:2.15
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:427.va6441fa17010
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
plain-credentials:1.7
plugin-util-api:2.10.0
popper-api:1.16.1-2
popper2-api:2.11.0-1
pubsub-light:1.16
role-strategy:3.2.0
saml:2.0.9
scm-api:2.6.5
script-security:1118.vba21ca2e3286
snakeyaml-api:1.29.1
sse-gateway:1.24
ssh-credentials:1.19
sshd:3.1.0
structs:308.v852b473a2b8c
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
workflow-aggregator:2.6
workflow-api:1108.v57edf648f5d4
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-durable-task-step:1112.vda00e6febcc1
workflow-job:1145.v7f2433caa07f
workflow-multibranch:696.v52535c46f4c9
workflow-scm-step:2.13
workflow-step-api:615.vb09dac339255
workflow-support:804.vba10a18a1476

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins Helm Chart `jenkins:3.10.2`
Jenkins Docker Image: `jenkins/jenkins:2.327-jdk11`

### Reproduction steps

1. Add input as an exclusion for OTEL plugin.
![image](https://user-images.githubusercontent.com/8277432/148080361-ea6e2eaf-7e40-40ba-94bb-53a7a4eaf6f4.png)
2. Create a pipeline (I'm using declarative) with an input step:
```groovy
pipeline {
  agent any
  stages {
    stage ('Test') {
      steps {
        echo 'Hello'
        sh script: 'echo Hello'
        input message: 'Click Proceed'
      }
    }
  }
}
```

### Expected Results

I would expect the `echo` and `input` steps to not appear in traces. While still seeing the `sh` step.

### Actual Results

I get the expected of not seeing `echo` and seeing `sh`. But I still see the `input` step appearing.

![image](https://user-images.githubusercontent.com/8277432/148081181-09d48570-7d58-48ef-8c36-7e9b1559abd3.png)

### Anything else?

The reason why I want to exclude `input` as it can often take a long period of time for someone to trigger the input, I don't want this time to be taken into account with the trace.

**Comment by BenB196** [comment]
Closing this issue. I upgraded to `1.1.1` and am no longer seeing this issue.

**Comment by cyrille-leclerc** [comment]
Hello @BenB196 , we run a survey to better understand Jenkins Observability needs and more broadly CI/CD Observability needs, could you by any chance answer it?
https://docs.google.com/forms/d/e/1FAIpQLSezbndR1bpPj4YeWquLLWEYOkEjEI-lSyNbtDUVrR-udpt2lA/viewform?usp=sf_link
