### ISSUE TITLE
Identify the node provider

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#34]
### Feature Request

In a CI environment with different type of agents, such as:
- static workers
- ephemeral workers.

And also different cloud providers, such as:
- GCE
- EC2
- K8s

I'd like to identify the node spans with their provider therefore I can easily monitor the providers easily.

I don't know if the FlowNode can provide those details, but if it's possible, should the span have a new label like the ones specified in:
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud.md
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md

**Comment by kuisathaverat** [comment]
Done by the libraries
https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/gcp-resources
https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/aws-resources
