### ISSUE TITLE
env file missing from demos directory

### ISSUE THREAD

**Issue by wajika** [jenkinsci/opentelemetry-plugin#349]
### Describe your use-case which is not covered by existing documentation.

![image](https://user-images.githubusercontent.com/17058349/156491145-8de16008-88f9-41a5-803d-70ccf7b495c3.png)
![image](https://user-images.githubusercontent.com/17058349/156491189-e918bd63-d15a-4b75-9d05-43cb61160711.png)

**Comment by cyrille-leclerc** [comment]
Hello @wajika  , we run a survey to better understand Jenkins Observability needs and more broadly CI/CD Observability needs, could you by any chance answer it?
https://docs.google.com/forms/d/e/1FAIpQLSezbndR1bpPj4YeWquLLWEYOkEjEI-lSyNbtDUVrR-udpt2lA/viewform?usp=sf_link

**Comment by wajika** [comment]
I've already submitted an answer, but we're not using jenkins, so there may not be as many submissions
@cyrille-leclerc

**Comment by kuisathaverat** [comment]
We do not use that file in our demos.
