### ISSUE TITLE
🚧 Parallel step does not work

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#36]
⚠️ 

### What

When using the parallel step to generate dynamically a bunch of parallel stages, the spans are not created

### Screenshots

![image](https://user-images.githubusercontent.com/2871786/111385760-2bf1f300-86a3-11eb-8389-d78fbe847a25.png)

![image](https://user-images.githubusercontent.com/2871786/111385796-36ac8800-86a3-11eb-839e-96f764fb8178.png)

### Configuration

- Jenkins LTs
- Latest version ->h ttps://github.com/jenkinsci/opentelemetry-plugin/commit/bc0eed04b7d257e9dceac017a8029082a150d573

### Actions

- [ ] Create the minimal example
- [ ] Provide debug traces

**Comment by cyrille-leclerc** [comment]
I thought I fixed it, maybe we have not released yet, or this would be an older version of the plugin

**Comment by v1v** [comment]
I'll verify if the existing installation is correct, maybe I messed up with the k8s and JCasC somehow.

**Comment by v1v** [comment]
False alarm!! Sorry about that.

The issue was related to a wrong deployment of k8s with an old version of the plugin

To illustrate what I meant, the latest version of the plugin provides those details

![image](https://user-images.githubusercontent.com/2871786/111538905-2c52c280-8765-11eb-9437-f64150506044.png)
