### ISSUE TITLE
Expose metrics on rate limit for GitHubSCMSource's

### ISSUE THREAD

**Issue by timja** [jenkinsci/opentelemetry-plugin#411]
### What feature do you want to see added?

Hi

We run a large GitHub organisation and recently collapsed our many folders down to 2

This led to us getting rate limited but not obviously it's only shown in the UI in a couple of places, if it's rate limited during a build then you'll just see what looks like hung jobs.

It would be good to be able to monitor for this.

I can probably contribute an implementation but do you have any suggestions on how this should work?

**Comment by cyrille-leclerc** [comment]
It's a great idea. I've started to look at this, I made little progress.

I suspect that the metrics we want to observe are private fields of the `org.kohsuke:github-api` library, of the `org.kohsuke.github.GitHubClient` object.

**Comment by timja** [comment]
The rate limit is available publicly,

https://github.com/jenkinsci/github-branch-source-plugin/blob/10a3514c2551bae8e4b8820c5ff3e224902f2f3d/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubAppCredentials.java#L660-L663
