### ISSUE TITLE
Capture declarative condition post conditions as spans (`always`, `cleanup`, `success`...) 

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#42]
### Feature Request

Introduce wrapping spans for families of post conditions in declarative pipelines: `always`, `changed`, `fixed`, `regression`, `aborted`, `success`, `unstable`,  `unsuccessful`, `failure`, `cleanup`.

- https://www.jenkins.io/doc/book/pipeline/syntax/#post-conditions
- https://www.jenkins.io/doc/pipeline/tour/post/

For instance:

```groovy
pipeline {
  agent any
  stages {
    stage ('Hello') {
      steps {
        echo "hello World"
      }
    }
  }
  post { 
        always { 
            sh 'echo "always"'
        }
        cleanup {
            sh 'echo "cleanup"'
        }
    }
}
```

Produces:

![image](https://user-images.githubusercontent.com/2871786/111916963-5f52ca00-8a75-11eb-92bf-75ea51c0b6f6.png)

**Comment by cyrille-leclerc** [comment]
You mean that you want to capture a "Post Condition" wrapping span, correct?
