### ISSUE TITLE
Add more attributes to the runs

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#45]
### Feature Request

Add some attributes regarding the run in order to help with the filtering:

#### Multibranch pipeline

* detect if the transaction is related to:
  * a branch
  * pul request
  * tag

#### All

* Build description, people might use it to add more context to the build. 
* build result (unstable, failure, aborted, success)
* build cause

For instance:

![image](https://user-images.githubusercontent.com/2871786/112044769-10269b00-8b42-11eb-811f-8945e8cb0605.png)

**Comment by cyrille-leclerc** [comment]
See recent improvements on the attributes of `git`and `checkout ...` spans where we now capture the git branch and the git user
