### ISSUE TITLE
Scalability Tests

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#49]
Scalability Tests

**Comment by cyrille-leclerc** [comment]
@v1v @kuisathaverat can we say that we have dogfooded enough to say that scalability tests have been conducted successfully?

**Comment by kuisathaverat** [comment]
It is running in a production-grade environment, this environment runs a few thousand jobs daily, with no issues so far. It is true that we did not make any stress tests. I think we can wait a week and close this issue.
