### ISSUE TITLE
Release 2.9.1 broken if logs are not stored in Elastic

### ISSUE THREAD

**Issue by timmjd** [jenkinsci/opentelemetry-plugin#498]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

* Install opentelemetry plugin 2.9.1
* Configure system to "Don't store pipeline logs in Elastic"
* Build a job and select the console output
* You will not see the logs but only an error about a missing logs visualization URL
![image](https://user-images.githubusercontent.com/508684/186536266-3baca593-9b74-462c-b8ec-5f779f52e416.png)

### Expected Results

See the logs if they are not send to Elastic

### Actual Results

See no logs

### Anything else?

Does work if "Store pipeline logs In Elastic and visualize logs exclusively in Elastic (logs no longer visible through Jenkins screens)" or "Store pipeline logs In Elastic and visualize logs both in Elastic and through Jenkins" is selected

**Comment by cyrille-leclerc** [comment]
Fixed in 2.9.2
