### ISSUE TITLE
Some API calls lack documentation

### ISSUE THREAD

**Issue by alsterg** [jenkinsci/opentelemetry-plugin#503]
### Describe your use-case which is not covered by existing documentation.

Example APIs are: setExporterTimeoutMillis, setExporterTimeoutMillis, setAuthentication​, setAuthentication​.
Although the names are to some degree self-descriptive, it is not entirely clear in every case. It would be nice to have a short description.

**Comment by alsterg** [comment]
Also it is not clear from the docs what are the default values, and what is are the necessary values that need to be set (minimum config).

**Comment by v1v** [comment]
Thanks @alsterg for raising this issue. To help with some documentation can be found under the [config.jelly](https://github.com/jenkinsci/opentelemetry-plugin/blob/master/src/main/resources/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration/config.jelly) file, those descriptions are set when using the Jenkins UI.

Some of those setters are related to the OpenTelemetry SDK customisation, https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/setup-and-configuration.md#configuring-the-jenkins-opentelemetry-plugin-using-opentelemetry-standard-environment-variables-and-system-properties

For each individual setter you mentioned see below:

* `setExporterTimeoutMillis`, it sets `OTEL_EXPORTER_OTLP_TIMEOUT`, as per the [otel-specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md), - `Maximum time the OTLP exporter will wait for each batch export.`
* `setAuthentication`, further details explained in https://github.com/jenkinsci/opentelemetry-plugin#getting-started (see `Authentication`). Or the helper description details that can be found in [authentication](https://github.com/jenkinsci/opentelemetry-plugin/tree/master/src/main/resources/io/jenkins/plugins/opentelemetry/authentication)
* `setExporterIntervalMillis `, similar to OTEL_IMR_EXPORT_INTERVAL , `SDK: export interval between pushes to the exporter`

I guess, we might need to enrich it so those details can be easily found without much trouble, some of those setters are defined as part of the OpenTelemetry SDK, so we could redirect to the original reference.

**Comment by v1v** [comment]
Accessing the internals might not be trivial for some people. I'm not sure if explaining how to use Groovy to configure the tool outside of JCasC will be broadly used or needed, in addition, it might require to update the docs if any changes in the internals -- and internals are not aimed to be consumed so breaking changes could happen at any moment of time.

For that reason, I'd suggest to use [JCasC](https://www.jenkins.io/projects/jcasc/) as explained in the [Configuration as Code (JCasC)](https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/setup-and-configuration.md#configuration-as-code-jcasc---jenkins-opentelemetry-plugin) section . We added several UTs to validate certain configurations, see the [jcasc](https://github.com/jenkinsci/opentelemetry-plugin/tree/master/src/test/resources/io/jenkins/plugins/opentelemetry/jcasc) folder
