### ISSUE TITLE
Elastic Observability Redirection URL is broken

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#51]
Redirection URL no longer works

Example: 
https://localhost:5601/app/apm/services/jenkins/transactions/view?rangeFrom=2021-03-24T11:25:53.019Z&rangeTo=2021-03-24T11:45:53.019Z&transactionName=scripted-pipeline-assigned-to-specific-node&transactionType=unknown&latencyAggregationType=avg

![image](https://user-images.githubusercontent.com/459691/112304359-ade2ad00-8c9d-11eb-824d-45bdf824691e.png)

**Comment by cyrille-leclerc** [comment]
Cause found: https://github.com/elastic/apm-server/issues/5006

**Comment by cyrille-leclerc** [comment]
Close as it's fixed for the integration architecture based on the Elastic Observability OTLP intake.

**Comment by v1v** [comment]
I'm testing it out https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/opentelemetry/0.9-beta-rc247.1bb66b864848/ that points to the latest build -> https://github.com/jenkinsci/opentelemetry-plugin/commit/1bb66b8648487813111c6425f5fe971407216bbc

![image](https://user-images.githubusercontent.com/2871786/112519971-d4364480-8d92-11eb-8965-a51a19fc2d13.png)

and the redirect is not working:

`<url>/app/apm/services/jenkins/transactions/view?rangeFrom=2021-03-25T17:29:24.964Z&rangeTo=2021-03-25T17:49:24.964Z&transactionName=hello%2FhelloWorld-k8s&transactionType=custom&latencyAggregationType=avg`

While if I use the below URL format, things are working correctly:

`<url>/app/apm/services/jenkins/transactions/view?rangeFrom=2021-03-25T17:19:50.048Z&rangeTo=2021-03-25T17:39:50.048Z&transactionName=hello/helloWorld-gcp&transactionType=unknown&latencyAggregationType=avg&traceId=c512df0689160c4d1e8f9cf51365af9a&transactionId=1e2c4a80b2d703aa`

The only differences are:
- traceId
- transactionId

**Comment by cyrille-leclerc** [comment]
@v1v I checked again and the new URL works well for me with Elastic Observability 7.12

**Comment by cyrille-leclerc** [comment]
Workaround: set all transactions to `type=unknown` waiting to have a consistent support of `type` across Elastic integration architectures.

**Comment by swilliams-dev** [comment]
> 

How do you do this?

**Comment by swilliams-dev** [comment]
I was able to get the link working by creating a custom observability backend in /configure that had my ES base url followed by: `/app/apm/services/${serviceName}/transactions/view?rangeFrom=${startTime.minusSeconds(600)}&rangeTo=${startTime.plusSeconds(600)}&transactionName=${rootSpanName}&transactionType=unknown&latencyAggregationType=avg&traceId=${traceId}&transactionId=${spanId}`

**Comment by cyrille-leclerc** [comment]
Sorry for the inconvenience.
Great "workaround".
It seems that we lost compatibility with Elastis 7.x in recent versions of the Jenkins Otel Plugin. We have to offer this compatibility again.
I reopen this issue waiting to clarify this problem.

**Comment by swilliams-dev** [comment]
Thanks! Glad to provide details if I can help.

**Comment by cyrille-leclerc** [comment]
@swilliams-dev I misunderstood your problem. I thought it was an incompatibility with the 7.latest (ie 7.17) version of Elastic. I'm sorry but 7.10 is the 2020 release, an Elastic version that didn't yet have native support for the OTLP protocol and that required to use the now deprecated [OpenTelemetry Collector Exporter for Elastic](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticexporter).

I am more inclined to document the "workaround" you identified rather than evolving the Otel Plugin for a setup that rely on components that have been deprecated a year ago.

Can you please share with us why you can't upgrade beyond Elastic 7.10? Why you can't upgrade to a recent 7.x version?

**Comment by swilliams-dev** [comment]
@cyrille-leclerc it is a bureaucratic limit based on the licensing model change, we are stuck with Apache 2.0: https://www.elastic.co/pricing/faq/licensing

If you have any old resources, I also hope to rig up the dashboard on 7.10.2.

**Comment by kuisathaverat** [comment]
it is resolved
