### ISSUE TITLE
Jenkins overview shows blank

### ISSUE THREAD

**Issue by Neelam-zanvar** [jenkinsci/opentelemetry-plugin#535]
![image](https://user-images.githubusercontent.com/98389856/195551692-d36cbdd3-2e44-43dc-a6c0-f1931eaf567b.png)
![image](https://user-images.githubusercontent.com/98389856/195552013-9992b81b-6644-4184-b9dc-cf5be47239b8.png)
![image](https://user-images.githubusercontent.com/98389856/195552253-8a7f5671-7a98-49fa-b770-52f02a1129e2.png)
![image](https://user-images.githubusercontent.com/98389856/195552478-58c45b66-d444-431d-9216-e41ef40132a5.png)
![image](https://user-images.githubusercontent.com/98389856/195552707-bf66c02d-5dfe-4e9b-a2fe-0bf3ecf9805d.png)
These are the configurations I've made. and on elk server i have only installed apm-server all are 8.4.2 version. The jenkins overview dashboard isnt loading

**Comment by v1v** [comment]
Thanks for reaching out.

Unfortunately,  there is no much we can do, there is no information regarding the controller, plugin version or even logs

We don't know much about your services and how they are configured, whether they can see each other l, the security or even the OTEL collector is enabled and configured 

I could guess from the screenshots:
1.  the apm server/OTEL collector connection is not authenticated,  is that the expected configuration? Is the APM server/OTEL connector configured withour any security?
2. Elastic usee doesnt have access to the elasticsearch

**Comment by Neelam-zanvar** [comment]
Well i am now able to see the dashboard. i had missed the import dashboard to kibana step. but i am still getting few metrics as blank
![image](https://user-images.githubusercontent.com/98389856/196094413-358ce40f-6946-4e44-a0d2-6b71651e3608.png)
![image](https://user-images.githubusercontent.com/98389856/196094504-3b21d15e-c837-4927-8d86-a72671efff8f.png)
![image](https://user-images.githubusercontent.com/98389856/196094610-1a38db59-852e-4771-bbe9-8e3333f4e774.png)

i am not using otel collector. sending metrics from jenkins to apm directly. apm has no authorization. elasticsearch has(i have added the correct credentials for connecting to elasticsearch still it shows the error as shown in the screenshot below
![image](https://user-images.githubusercontent.com/98389856/196094899-47333a7d-5d42-4708-85b9-6c0d332b7d1e.png)

elk stack and apm server version is 8.4.2
jenkins version is [Jenkins 2.361.2]
opentelemetry plugin version2.9.2

no logs on jenkins side
![image](https://user-images.githubusercontent.com/98389856/196095500-96399a95-d650-4e42-ae40-41def347d3f3.png)

getting these for apm server

**Comment by v1v** [comment]
Unfortunately, I cannot provide any answers as I don't know the existing networking topology for your existing services and whether they can see each other.

I can say there are some errors in the screenshots you provided:

```
Failed to connect to ... 401: Unauthorized
```

I tried your setup with the demo environment:
- Jenkins core 2.361.2
- OpenTelemetry Plugin 2.9.2
- Elastic STack 8.4.2
- APM Server without authentication

And it worked fine, you can try my demo in
- https://github.com/v1v/opentelemetry-plugin/tree/feature/use-8.4.2

Then run the below commands

```bash
$ make -C demos build
$ make -C demos start-all
```

Open your browser with the URL `http://localhost:8080/` and run some Jenkins jobs then you will see those traces in `http://localhost:5601/app/apm/services/jenkins/overview?comparisonEnabled=true&environment=ENVIRONMENT_ALL&kuery=&latencyAggregationType=avg&offset=1d&rangeFrom=now-15h&rangeTo=now&serviceGroup=&transactionType=request`

You can see the Jenkins logs specific for the OpenTelemetry plugin in `http://localhost:8080/manage/log/Otel/`

Unfortunately, I don't know if you have configured the APM Server with the authentication, but if `Agent authorization` has been configured in the APM Server integration, that could be the problem. 

Finally the configuration of any OTEL vendors is not something we handle individually within this project.

**Comment by v1v** [comment]
> while configuring the plugin also i am getting errors as shown in screenshots previously.

Already reported on https://github.com/jenkinsci/opentelemetry-plugin/issues/437

**Comment by Neelam-zanvar** [comment]
is using fleet server and collector mandatory?



Best regards,

Neelam Zanvar Hanabaratti

Infrastructure & DevOps Engineer

Mobile: +91 8792429745

www.minutuscomputing.com<https://www.minutuscomputing.com/>

________________________________

**Comment by v1v** [comment]
> is using fleet server and collector mandatory?

No, this plugin works with all the Vendors that support OpenTelemetry natively or they have support with the OpenTelemetry collector:

- https://opentelemetry.io/vendors/
- https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by Neelam-zanvar** [comment]
Okay thank you for your support and time. I'll go through the links you've sent

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
