### ISSUE TITLE
The field "jenkins.agents.total" associated with this object no longer exists in the index pattern. Please use another field.

### ISSUE THREAD

**Issue by Neelam-zanvar** [jenkinsci/opentelemetry-plugin#536]
On the jenkins overview dashboard i am not getting any node data
![image](https://user-images.githubusercontent.com/98389856/195788805-221dfb76-0532-4ae2-aeb7-5517332dda1c.png)
![image](https://user-images.githubusercontent.com/98389856/195789011-6430576e-5b8e-4103-9ffd-aeeae2e8f0a0.png)
also there is no queue data. when i click on edit visualisation i am getting this error The field "jenkins.agents.total" associated with this object no longer exists in the index pattern. Please use another field. and in jenkins logs i am getting 1i.j.p.o.j.OtelEnvironmentContributorService#addEnvironmentVariables: MonitoringAction NOT found on run arc #1
 I dont understand what i am missing. looks like some issue with the index

**Comment by v1v** [comment]
Thanks for reporting this. Duplicates https://github.com/jenkinsci/opentelemetry-plugin/issues/437
