### ISSUE TITLE
OtelEnvironmentContributorService#addEnvironmentVariables: MonitoringAction NOT found

### ISSUE THREAD

**Issue by Neelam-zanvar** [jenkinsci/opentelemetry-plugin#552]
Installed opentelemetry plugin on jenkins to send build logs to elastic APM. Getting this error in jenkins.log.

OtelEnvironmentContributorService#addEnvironmentVariables: MonitoringAction NOT found
![image](https://user-images.githubusercontent.com/98389856/200480878-457fb52b-d5c9-42a9-93fb-9b46123fd0a9.png)

 how can i setup the environment variable

**Comment by v1v** [comment]
Please fill the form when raising an issue with further details, such as, versions, environment and how to reproduce the issue. Otherwise, screenshots don't provide enough context to provide any valuable help

Thanks

**Comment by v1v** [comment]
https://github.com/jenkinsci/opentelemetry-plugin/issues/new?assignees=&labels=bug&template=1-report-bug.yml is the default template you can use

**Comment by v1v** [comment]
@Neelam-zanvar I'll close this issue now, feel free to reopen it with more details 
Thanks
