### ISSUE TITLE
OTEL reports transaction with negative latency to APM

### ISSUE THREAD

**Issue by SenthilkumarRasan** [jenkinsci/opentelemetry-plugin#562]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

enabled otel plugin for our cd jenkins and see discrepancy in response time and some with negative latency

### Expected Results

Latency same as we see in jenkins console

### Actual Results

Attached snapshot with negative response time

**Comment by SenthilkumarRasan** [comment]
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/34168946/203403064-023e0928-bd9e-44b8-bce3-e4d104b79103.png">

**Comment by v1v** [comment]
Unfortunately, all the details in the issue regarding the environment, version are empy

In addition,  if you can provide further details about what vendor you are using and how to reproduce the issue, without those details and only a screenshot there will be nothing we can do to help

Thanks

**Comment by SenthilkumarRasan** [comment]
we are using jenkins version 2.361 with opentelemetry plugin 2.10. We use elastic APM as backend with version 8.5. One few few trace has negative response time whereas other are fine. Jenkins job has positive response time whereas data from opentelemetry has negative latency with no traces for the job. I am not sure how u can reproduce this as our CD jobs has multi step pipeline and we dont see the issue all the time.

**Comment by cyrille-leclerc** [comment]
Hello @SenthilkumarRasan ,

Can you please provide us more context:
* What is the duration of the Jenkins job that has a negative duration reported in Elastic APM
* What is the architecture in place? Is the Jenkins controller configured to send the traces directly to Elastic APM server or are they sent to an OpenTelemetry Collector that sends the data to Elastic?
* Can you export the Elasticsearch data of the trace causing problems? @v1v may guide you to achieve this, I don't have an Elastic test environment
* Can you share the Jenkinsfile of the pipeline that is facing a problem?

Can you try to reproduce the problem sending the data to another trace analytics solution like Jaeger? The best solution to do so is to setup an OpenTelemetry Collector configured to send traces both to Elastic APM and to Jaeger. An alternative if you can't setup an OpenTelemetry Collector could be to temporarily configure the Jenkins Controller to send traces to Jaeger.
We can guide you on this if you are not familiar with Jaeger or with the OpenTelemetry Collector.

**Comment by SenthilkumarRasan** [comment]
Thanks. Trying to use new relic backend for opentelemetry data from jenkins. Do u have option to add link from jenkins job to new relic transaction trace and dashboard like elastic APM? will update the stats once we run some pipeline and get the data in newrelic.

**Comment by SenthilkumarRasan** [comment]
With elastic APM backend we have link from every job to transaction trace in elastic APM and link to dashboard from jenkins jobs page. I dont see similar option with newrelic as backend. Is there additional configuration required to get similar integration from jenkins console to NEWRELIC

**Comment by v1v** [comment]
@SenthilkumarRasan , to help with your question regarding New Relic, there is no specific integration in the UI, though the custom observability backend could help, those details are roughly explained in the Getting Started section, see below:

> Visualization: add the backend used to visualize job executions as traces.
Elastic Observability
...
Custom Observability backend for other visualization solutions

Regarding the original request, did you manage to get some answers that Cyrille asked in a previous comment?

**Comment by kuisathaverat** [comment]
I can not replicate it on 2.16
