### ISSUE TITLE
Leverage the sh/bat steps with the system that interact with

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#6]
### What

Allow to create span labels dynamically for the steps if they have an environment variable set.

### Why

Some pipeline steps interact with third party services. This could help to enhance the transactions/spans with more information about what are the services they interact with.

### Design

Env variables could be set dynamically based on the below nomenclature:

* `OTEL_STEP_<ATTRIBUTE_NAME>`

Then `<ATTRIBUTE_NAME>` will be replaced accordingly,

```
spanBuilder.setAttribute("OTEL_STEP_FOO", "foo")
```

### Some ideas

Given the step:

```groovy
pipeline {
  ...
  stages {
    stage('login') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-login',
                                          passwordVariable: 'pass',
                                          usernameVariable: 'user')]) {
          sh 'docker login -u $user -p $pass my.docker.registry'
        }
      }
   }
}
```

I'd like to create a span with the `sh` step, but also saying that the thirdparty system that interacts with is `my.docker.registry`.

Therefore, a potential implementation (if possible) could be if the env variable `OTEL_STEP_SERVICE` is set, see below:

```groovy
pipeline {
  ...
  stages {
    stage('login') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-login',
                                          passwordVariable: 'pass',
                                          usernameVariable: 'user')]) {
          withEnv(['OTEL_STEP_SERVICE=my.docker.registry']) {
            sh 'docker login -u $user -p $pass $OTEL_STEP_SERVICE'
          }
        }
      }
   }
}
```

Then `OTEL_STEP_SERVICE` will help to identify the system that the step interacts with.

**Comment by cyrille-leclerc** [comment]
I'm wondering if we should introduce some OpenTelemetry steps to expose `io.opentelemetry.api.trace.Span#updateName(newName)`  and  `io.opentelemetry.api.trace.Span#setAttribute(key, value)`

**Comment by cyrille-leclerc** [comment]
The first improvement could be to use the `label` attribute of the shell steps (`sh`...): https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#sh-shell-script

**Comment by v1v** [comment]
>I'm wondering if we should introduce some Jenkins pipeline steps to expose io.opentelemetry.api.trace.Span#updateName(newName) and io.opentelemetry.api.trace.Span#setAttribute(key, value).
@v1v would this solve your problem?

Do you mean something like the below snippet?

```groovy
pipeline {
  ...
          ...
          spanService(name: 'my.docker.registry') {
            sh 'docker login -u $user -p $pass $OTEL_STEP_SERVICE'
          }
          ...
}
```

If so, will it be possible to populate the parent span attributes to the child `sh` span?

**Comment by cyrille-leclerc** [comment]
For this shell step, i was thinking of using the `label` attribute of the `sh` step (`label: docker/login my.docker.registry`). The limit in my rationale is that I can just set the span name and not inject span attributes like `jenkins.pipeline.step.type: docker/login`.

⚠️  Note that I'm not sure that it's a good idea to name the span , the best could be to use the [Semantic conventions for RPC spans](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md) with a span name `docker/login` and  attributes `net.peer.name: my.docker.registry`, `rpc.service: docker`, `rpc.method: login`, `rpc.system: http`. Following the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md) would require a wrapping step similar to what you suggested.

```
pipeline {
          ...
          withCredentials([usernamePassword(
               credentialsId: 'dockerCredentials', 
               usernameVariable: 'USERNAME', 
               passwordVariable: 'PASSWORD')]) {

          sh (label: 'docker/login my.docker.registry', script: 'docker login -u $USERNAME -p $PASSWORD")
          ...
}
```

**Comment by v1v** [comment]
I've been thinking about this particular feature and came up with the below idea.

People can opt-in if the step they call supports the `apm` attributes, therefore we could allow people to use a new key in their call. This will only work for steps that don't have an argument validation. 

Unfortunately, the step itself should provide the DataBoundSetter for the `apm` argument:

```
pipeline {
  ...
          ...
          theStep(..., apm: [ 'net.peer.name': 'my.docker.registry', 'rpc.service': 'docker', 'rpc.method': 'login', 'rpc.system': 'http']
          ...
}
```

If we like the above, we could even move forward and enhance the built-in steps to support the above, though we might need to raise an RFC to request such a functionality in the Jenkins Core and the Pipeline plugins, since there is a signature validation and unexisting parameters are not allowed (`WorkflowScript: 8: Invalid parameter "apm", did you mean "label"?`)

To illustrate the above:

```groovy
pipeline {
  ...
          ...
          sh(label: 'docker login', script: 'docker login -u $user -p $pass $OTEL_STEP_SERVICE', apm: [ 'net.peer.name': 'my.docker.registry', 'rpc.service': 'docker', 'rpc.method': 'login', 'rpc.system': 'http'])
          ...
}
```

Why do I like this approach?
1) Development experience, there will be always a new argument to leverage the existing attributes when using the plugin.
2) Distributed traces to be a first citizen and supported by the Jenkins core (or workflows) by default.

In order to test the above I did raise the below changes:
1) In the plugin itself -> https://github.com/jenkinsci/opentelemetry-plugin/pull/64
2) In the durable task plugin -> https://github.com/v1v/workflow-durable-task-step-plugin/commit/adc9afa3d5761eb6aa358cf16e1e809610ecf5bd


Tests:

```
node() {
    echo 'Hello World'
    sh(script: 'echo hi',  apm: [ 'net.peer.name': 'my.docker.registry', 'rpc.service': 'docker', 'rpc.method': 'login', 'rpc.system': 'http'])
}
```

Produced the below log traces

```
Apr 10, 2021 1:33:02 PM INFO io.jenkins.plugins.opentelemetry.job.CommonStepHandler createSpanBuilderFromApmDetails
Create apm {net.peer.name=my.docker.registry, rpc.service=docker, rpc.method=login, rpc.system=http}
```

And the span attributes are properly added:

![image](https://user-images.githubusercontent.com/2871786/114269983-c96de780-9a01-11eb-885d-35265effcefa.png)


What do you think?

**Comment by cyrille-leclerc** [comment]
Close: we recommend to use the `sh(label='xxx',...)` and the `otel-cli` to add context
