### ISSUE TITLE
Missing parameter how to remove sh scripts from tracing

### ISSUE THREAD

**Issue by worldcompass** [jenkinsci/opentelemetry-plugin#609]
### Describe your use-case which is not covered by existing documentation.

Background:
using opentelemetry plugin with hashicorp-vault-plugin causes secrets that are retrieved from vauld to be printed in sh/bash scripts in console output only for jenkins agents.

Disabling opentelemetry fixes the issue, but we would like to use it in the future for our project.

Example of pipeline that prints secrets as plain text:
```
node('agent1'){
    def configuration = [vaultUrl: 'https://vault-url,
                         vaultCredentialId: 'd46974e1-8374-4048-bf5b-e63897604bcb',
                        engineVersion: 2]


    def secrets = [
            [path: 'dmitriyvovk/test', engineVersion: 2, secretValues: [
                        [envVar: 'test', vaultKey: 'test'],
            ]]
]
    withVault([configuration: configuration, vaultSecrets: secrets]){
        sh'''
        echo $test
        '''
    }
}

```
but note that `print,echo` as groovy steps are masking secrets as expected.

Could you please advise how to mark them as `*****` as it was previously?

**Comment by kuisathaverat** [comment]
Check the doc page of that plugin, it has a bug that does not mask properly the secret https://www.jenkins.io/security/advisory/2023-05-16/#SECURITY-3077
https://plugins.jenkins.io/hashicorp-vault-plugin/
