### ISSUE TITLE
Propagate trace context from Jenkins HTTP API calls to triggered builds

### ISSUE THREAD

**Issue by jremond** [jenkinsci/opentelemetry-plugin#617]
### What feature do you want to see added?

Propagate trace context when a build is triggered by a [Jenkins HTTP API](https://www.jenkins.io/doc/book/using/remote-access-api/) call (ie `JENKINS_URL/job/JOBNAME/build` or `JENKINS_URL/job/JOB_NAME/buildWithParameters`).

**Comment by cyrille-leclerc** [comment]
That's an exciting use case and a great idea!
Can you please share with us how you trigger  the Jenkins jobs so that we understand on which entry point we want to propagate the trace context?

**Comment by cyrille-leclerc** [comment]
Research notes for myself for the context propagation from a Jenkins API call to the job execution

```
jenkins.model.ParameterizedJobMixIn.ParameterizedJob#doBuild
jenkins.model.ParameterizedJobMixIn#doBuild


jenkins.model.ParameterizedJobMixIn#getBuildCause
jenkins.model.Jenkins#getQueue
hudson.model.Queue#scheduleInternal
```

**Comment by wadarochi** [comment]
Perhaps we can make withSpanAttribute support setting traceparent, so that a proxy job can be responsible for receiving the traceparent parameter in the HTTP API, and subsequent jobs can attach to this traceparent.
