### ISSUE TITLE
Kibana dashboard URL parameters is not used

### ISSUE THREAD

**Issue by loopping** [jenkinsci/opentelemetry-plugin#618]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.375.3.5
OS: Linux - 4.18.0-425.3.1.el8.x86_64
Java: 11.0.18 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
...
opentelemetry:2.11.0
...

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux - 4.18.0-425.3.1.el8.x86_64

### Reproduction steps

In manage/configure/OpenTelemetry
Set Display Kibana dashboard link to true
Set Kibana dashboard URL parameters to
`title=${kibanaDashboardTitle}&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-12h%2Fh,to:now))`
We change the time frame from -24h to -12h just to demonstrate

### Expected Results

In jenkins home, the "Elastic Obervability" link should reflect the change from -24h to -12h

### Actual Results

In jenkins home, the "Elastic Obervability" link is the default

### Anything else?

In https://github.com/jenkinsci/opentelemetry-plugin/blob/master/src/main/java/io/jenkins/plugins/opentelemetry/backend/ElasticBackend.java#L170
It seems that a part of the URI is hard coded.

The getKibanaDashboardUrlParameters function is never called.

**Comment by kuisathaverat** [comment]
confirmed in 2.16, The setting changes in the preferences, but it is not applied.
