### ISSUE TITLE
Store Jenkins Freestyle jobs console log in an OTLP backend like Elastic

### ISSUE THREAD

**Issue by Geni2** [jenkinsci/opentelemetry-plugin#654]
### Describe your use-case which is not covered by existing documentation.

I was going through the documentation to implement OpenTelementry in Jenkins to be able to send Jenkins console logs into Elastic but in the documentation, I notice that OpenTelementry doesn't support every job in Jenkins like "Freestyle". 
Have someone used openTelementry for Freestyle jobs? 

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/build-logs.md#can-the-jenkins-server-logs-and-the-logs-of-other-types-of-jobs-like-freestyle-or-matrix-jobs-be-sent-through-opentelemetry-to-be-stored-outside-of-jenkins

**Comment by cyrille-leclerc** [comment]
@Geni2 I'm unfortunately not aware of any API in Jenkins to send he build logs of other job types than Pipeline (eg Freestyle, Maven, Matrix...).

**Comment by kuisathaverat** [comment]
There is no good way to make it.
