### ISSUE TITLE
Add span traces steps to help with distributes traces in any Jenkins shared library

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#66]
### Feature Request

A Jenkins shared library step does not match any span since it is not a FlowNode, but a wrapper that called some other built-in steps (either the ones provided by the Jenkins Core/Workflow or plugins).

Let's support a couple of steps to enable the distributed traces in any shared library explicitly:

`openSpan` (with some parameters)
`closeSpan` (with some parameters)
`createSpan` (with some parameters and a closure)

To illustrate the above I'll use some a couple of examples (using the https://www.jenkins.io/doc/book/pipeline/shared-libraries/#defining-a-more-structured-dsl)

```groovy
// vars/buildPlugin.groovy
def call(Map config) {
    node {
        git url: "https://github.com/jenkinsci/${config.name}-plugin.git"
        sh 'mvn install'
        mail to: '...', subject: "${config.name} plugin build", body: '...'
    }
}
```

The above-mentioned new steps should help us to create a span:

```groovy
// vars/buildPlugin.groovy
def call(Map config) {
    String spanId = openSpan(...)
    node {
        git url: "https://github.com/jenkinsci/${config.name}-plugin.git"
        sh 'mvn install'
        mail to: '...', subject: "${config.name} plugin build", body: '...'
    }
    closeSpan(spanId: id)
}
```

Or using the closure:

```groovy
// vars/buildPlugin.groovy
def call(Map config) {
    createSpan(...) {
        node {
            git url: "https://github.com/jenkinsci/${config.name}-plugin.git"
            sh 'mvn install'
            mail to: '...', subject: "${config.name} plugin build", body: '...'
        }
    }
}
```

**Comment by cyrille-leclerc** [comment]
Great idea. I'm wondering how we could expose a subset of the OpenTelemetry API directly in the Jenkins pipeline language:
* `io.opentelemetry.api.trace.Tracer#spanBuilder()`
* `io.opentelemetry.api.trace.SpanBuilder#startSpan()`
* `io.opentelemetry.api.trace.Span#current()`
* `io.opentelemetry.api.trace.Span#end()`

**Comment by kuisathaverat** [comment]
To open, close spans manually is error-prone, it has to be something that has a context that open and closes the span.

withSpanAttributes implement it https://github.com/jenkinsci/opentelemetry-plugin/pull/827
