### ISSUE TITLE
SpanID is the same for all log lines

### ISSUE THREAD

**Issue by davnerson-dn** [jenkinsci/opentelemetry-plugin#669]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.401.2
OS: Linux - 5.3.0-1030-aws
Java: 11.0.19 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
opentelemetry:2.13.0

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 18.04 (EC2 0n AWS)

### Reproduction steps

Build logs are sent to Opentelemetry Collector container that send them to Loki.
Build traces are sent t OpenTelemetry Collector container that send them to Tempo.
Traces in tempo are shown correctly with a unique SpanID for each stage/step

### Expected Results

Logs atrributes in Loki contain the spanId that correspond to the spanId in Tempo

### Actual Results

All the logs lines contain the same SpanId which is the root spanId of the build

### Anything else?

i printed the environment variables to check the value of SPAN_ID and indeed its value change during the build to take the spanID of the current stage/step and spanId's are good in Tempo so looks like the bug is only in sending the info in the log attributes
This is the pipeline 
![Screenshot 2023-07-09 at 17 13 27](https://github.com/jenkinsci/opentelemetry-plugin/assets/85820962/1658702c-cba0-48c3-bab7-3b755e35c786)
In the Loki log all lines have the same SpanID
Notice the SPAN_ID variable has a different value 
![Screenshot 2023-07-09 at 17 11 06](https://github.com/jenkinsci/opentelemetry-plugin/assets/85820962/e10ddea9-e2a2-4271-9bb6-78396f3efdbe)
This value is the span of the step as we can see in the trace in Tempo
![Screenshot 2023-07-09 at 17 12 31](https://github.com/jenkinsci/opentelemetry-plugin/assets/85820962/8d0fa212-5492-404e-b127-fc1e2ae5253a)

But the SpanID in the atrribute is of the root span of the trace
![Screenshot 2023-07-09 at 17 18 01](https://github.com/jenkinsci/opentelemetry-plugin/assets/85820962/7fe154be-9f49-40bd-8ced-7afd87db9f2e)

**Comment by cyrille-leclerc** [comment]
look like a bug

**Comment by davnerson-dn** [comment]
adding some info:
i receive logs with error form Span functions like `putSpan`:
This is the function call:
`
putSpan(test-davnerson #140,SdkSpan{traceId=aae0224900a2d34d643f3113ff101774, spanId=fc15eeca17d78385, parentSpanContext=ImmutableSpanContext{traceId=aae0224900a2d34d643f3113ff101774, spanId=8bfe21344466b3e1, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, name=Phase: Start, kind=INTERNAL, attributes=null, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1689493210289919256, endEpochNanos=0}) - new stack: RunSpans{runPhasesSpans=[SdkSpan{traceId=aae0224900a2d34d643f3113ff101774, spanId=8bfe21344466b3e1, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=BUILD test-davnerson, kind=SERVER, attributes=AttributesMap{data={type=job, ci.pipeline.name=test-davnerson, ci.pipeline.run.number=140, ci.pipeline.type=workflow, ci.pipeline.run.url=https://jenkins-aws8.dev.drivenets.net/job/test-davnerson/140/, ci.pipeline.id=test-davnerson, ci.pipeline.run.committers=[], ci.pipeline.run.cause=[UserIdCause:davnerson-dn]}, capacity=128, totalAddedValues=8}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1689493210289863000, endEpochNanos=0}, SdkSpan{traceId=aae0224900a2d34d643f3113ff101774, spanId=fc15eeca17d78385, parentSpanContext=ImmutableSpanContext{traceId=aae0224900a2d34d643f3113ff101774, spanId=8bfe21344466b3e1, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, name=Phase: Start, kind=INTERNAL, attributes=null, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1689493210289919256, endEpochNanos=0}], pipelineStepSpansByFlowNodeId={}}
`
and this is the error i get in the log:
JSONParserErr
Value looks like object, but can't find closing '}' symbol
<img width="1220" alt="Screenshot 2023-07-16 at 10 52 02" src="https://github.com/jenkinsci/opentelemetry-plugin/assets/85820962/0f8af4c0-259e-4be2-9aff-904b7983e677">

**Comment by cyrille-leclerc** [comment]
I'm working on it.
First step is:
* https://github.com/jenkinsci/opentelemetry-plugin/pull/695

**Comment by cyrille-leclerc** [comment]
Once #695 is merged, we will be in a good shape to fix this bug

**Comment by cyrille-leclerc** [comment]
Merged, we just need to release now

**Comment by cyrille-leclerc** [comment]
Please test:
- https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-2.17.0-beta1

**Comment by cyrille-leclerc** [comment]
Please upgrade to 2.17
