### ISSUE TITLE
[Feat] Span propagation betwen remote trigged builds 

### ISSUE THREAD

**Issue by topikachu** [jenkinsci/opentelemetry-plugin#679]
### What feature do you want to see added?

We have several Jenkins instances and there are some jobs that are triggered remotely.
It seems there's no span propagation between these jobs even I add "traceparent" header.

Also, I check the code 'OpenTelemetryServletFilter.java', it always creates a span without a parent.

**Comment by cyrille-leclerc** [comment]
Fixed by 
* https://github.com/jenkinsci/opentelemetry-plugin/pull/682
