### ISSUE TITLE
Add Incrementals to plugin and allow installation builds per commit

### ISSUE THREAD

**Issue by DuMaM** [jenkinsci/opentelemetry-plugin#717]
### What feature do you want to see added?

https://www.jenkins.io/doc/developer/plugin-development/incrementals/#:~:text=With%20incrementals%2C%20we%20can%20create,and%20switching%20between%20incremental%20versions.

There is a feature which allows to tests and prepare package for every commit.
It doesn't have to be installed, but I will allow enabling prototyping some new changes which are affected by a few users.

**Comment by kuisathaverat** [comment]
duplicated https://github.com/jenkinsci/opentelemetry-plugin/issues/712
