### ISSUE TITLE
Is it possible to capture arguments passed into the plugins?

### ISSUE THREAD

**Issue by jamie-harness** [jenkinsci/opentelemetry-plugin#730]
### What feature do you want to see added?

Sorry, I'm not sure if this is the right place to post, there might already be a solution/configuration to it.

I noticed that for git plugin, it traces the repository. But for other plugins what's passed in is not traced. For example 
`sh(label: 'Maven install', script: 'mvn -Dmaven.test.failure.ignore=true clean package')`
does not trace the shell script part.

Is there a way to get that information? 

Thanks in advance

**Comment by cyrille-leclerc** [comment]
Thanks Jamie for your interest in the Jenkins OpenTelemetry plugin.
We have not implemented the collection of the shell script as it can be a very long character large object that are ,not suited to be captured as span attributes.

Moreover, our recommendation is for users to instrument their shell script with tools like the `otel-cli` our like instrumentation of build tools similar to the instrumentation of Maven or JUnit.

How would you imagine such capture of the "sh" step script details in the Jenkins OpenTelemetry plugin?

**Comment by kuisathaverat** [comment]
If you need the command executed it is the logs associated with the step ran, the attribute `span.id` and `labels.jenkins_pipeline_step_id` are the same in the step span and the log line.
