### ISSUE TITLE
SERVICE_NAMESPACE_AND_NAME does not play nicely with Tempo tags

### ISSUE THREAD

**Issue by chewrocca** [jenkinsci/opentelemetry-plugin#750]
### What feature do you want to see added?

SERVICE_NAMESPACE_AND_NAME does not seem to play nicely with Tempo tags in [Grafana Tempo Datasource](https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#variables-that-can-be-used-in-a-custom-query)

This line seems to build the Grafana Loki logs query:

https://github.com/jenkinsci/opentelemetry-plugin/blob/c03877572faca269d3691d1349976aebcf603ba9/src/main/java/io/jenkins/plugins/opentelemetry/backend/grafana/GrafanaLogsBackend.java#L66

I don't think we can have two keys in Tempo Datasource. In this case, `service.name` and `service.namespace` map to one value (that would be nice).  I was trying to follow the [OpenTelemetry Loki Exporter ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md#labels) to drop `service.namespace` which should mean "If `service.name` is present and `service.namespace` is not present then `job=service.name` is set."  

Without Tempo Datasource mapping two keys to one value, or allowing this Grafana Loki logs query to have only `service.name` it's making traces to logs correlations a bit challenging.

**Comment by chewrocca** [comment]
This issue seems related.  https://github.com/grafana/loki/issues/4553

**Comment by cyrille-leclerc** [comment]
Please see new release v2.19.0, you can configure sending logs to Loki and have links to navigate to Grafana for visualization.

You will also see how we do querying and exploration of Loki logs.

Please note that the decision to produce the `job` and `instance` labels when mapping OTLP logs to Loki is not the decision of the Jenkins OpenTelemetry plugin, it's the overall mapping currently defined by the [OTel Collector Loki Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md) that is going through many improvements at the moment. We acknowledge that having to parse OTel logs persisted in Loki using the `json` parsing is a form of boilerplate and the Loki project is working at simplifying this.

Please tell us how v2.19.0 helps you.

https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-2.19.0

**Comment by chewrocca** [comment]
I believe my real issue is with the tracesToLogsV2 tags and custom query within the Tempo datasource configuration.  I'll open an issue with them.  They need a way to match two tag keys, in this case service.namespace/service.name to one value  called job.

**Comment by cyrille-leclerc** [comment]
Understood @chewrocca . Note that on Grafana Cloud, you can use [Grafana Cloud Application Observability](https://grafana.com/docs/grafana-cloud/monitor-applications/application-observability/) where we have solved this trace2logs question.

@mar4uk please see this interesting use cas where curent Loki labels for OTel logs makes it difficult to implement trace2logs with standard Grafana capabilities.
