### ISSUE TITLE
View as plain text" under Console Output still displaying when external logging is setup.

### ISSUE THREAD

**Issue by chewrocca** [jenkinsci/opentelemetry-plugin#753]
### What feature do you want to see added?

Is it possible to avoid confusion by ignoring the "View as plain text" under Console Output? That link didn't do anything once the Grafana Logs were set up.

**Comment by kuisathaverat** [comment]
I am not sure if removing actions from the job is possible, but yes, it probably worth taking a look. In case is not possible, to show a message in the "View as plain text" informing that logs are stored remotely will avoid users confusion.

**Comment by kuisathaverat** [comment]
We cannot remove the `Console Output` or the  `View as plain text` action from the side panel are defined in the [Pipeline side panel](https://github.com/jenkinsci/workflow-job-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/sidepanel.jelly#L35). Also, adding a new action to go to the logs cause more confusion to the UI, so let's keep it as it is now.
