### ISSUE TITLE
Add additional prometheus labels to metrics

### ISSUE THREAD

**Issue by ehuizar1028** [jenkinsci/opentelemetry-plugin#834]
### What feature do you want to see added?

Not sure if this is possible, and I could not figure out if the feature exists, but is it possible to add additional labels to prometheus metrics from within jenkins? 

Example: 
`jenkins.executor.online` metric has a label that has the name of the build. Could we add additional labels to this metric? Seems like it's possible since the label can define the build name. Additional info like this can help create leaderboards in prometheus/grafana such as most running builds, most github repos checked out, etc. 

I've also tried using opentelemetry collector processors such as `metricstransform` and `attributes` with upsert actions, but nothing seems to work.

**Comment by cyrille-leclerc** [comment]
Can you please provide examples with the metric name and the attributes/labels you would like to add?

**Comment by shaiajneh** [comment]
@cyrille-leclerc 
Hey, 
Is it possible to add build name as a label to ci_pipeline_run_completed or ci_pipeline_run_failed?

**Comment by kuisathaverat** [comment]
At pipeline level you can use the following steps:

* withSpanAttribute(key, value[, type][, target])
* setSpanAttributes([spanAttribute(key, value[, type][, target])])
* withSpanAttributes([spanAttribute(key, value[, type][, target])])

see https://github.com/jenkinsci/opentelemetry-plugin/blob/main/docs/job-traces.md

At the Jenkins Controller level to build agent level, you can use `otel.resources.atributtes` java property to the environment variable `OTEL_RESOURCE_ATTRIBUTES`

see https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/

**Comment by cyrille-leclerc** [comment]
And please see the coming metrics:
- https://github.com/jenkinsci/opentelemetry-plugin/pull/959

Should be released in a few days
