### ISSUE TITLE
Send Logs To Loki while Still Preserving Console Output

### ISSUE THREAD

**Issue by BbBaboo42** [jenkinsci/opentelemetry-plugin#841]
### What feature do you want to see added?

In the Grafana Visualization Observability Backend, you currently must choose between:
1. Don't store pipeline logs in Loki
2. Store pipeline logs In Loki and visualize logs exclusively in Grafana (logs no longer visible through Jenkins screens)

While I do want the logs to be sent to Loki, I still need for the Console Output to exist, for other Jenkins plugins such as BlueOcean, Pipeline Overview and others.

**Comment by chewrocca** [comment]
I believe this may be related.  https://github.com/jenkinsci/opentelemetry-plugin/issues/773

**Comment by BbBaboo42** [comment]
I now see that configuring otel.logs.mirror_to_disk=true in the plugin configuration does achieve my goal.
However, It is very strange that for me to collect the build logs to loki, I have to add a Grafana Visualization Backend, and under its advanced option choose:
Store pipeline logs in Loki and visualize logs exclusively in Grafana (logs no longer visible through Jenkins Controler)

Which I then supposed to cancel out with the configuration otel.logs.mirror_to_disk=true

**Comment by cyrille-leclerc** [comment]
See
* https://github.com/jenkinsci/opentelemetry-plugin/pull/858

**Comment by cyrille-leclerc** [comment]
FYI PR above is merged and released

FYI New feature in progress to close the gap:
* https://github.com/jenkinsci/opentelemetry-plugin/pull/865

**Comment by cyrille-leclerc** [comment]
Solved by 
* https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/3.1261.v46101e2a_3660
![image](https://github.com/jenkinsci/opentelemetry-plugin/assets/459691/75028bb5-f7a1-4ef7-9378-3c156bf0d3bb)
