### ISSUE TITLE
Integrate Jenkins OpenTelemetry with Gradle OpenTelemetry

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#850]
### What feature do you want to see added?

Gradle supports OTel instrumentation through the https://github.com/craigatk/opentelemetry-gradle-plugin
We want the same OpenTelemetry integration of Gradle builds with Jenkins as we have with Maven builds.

### Upstream changes

Hopefully no change if the [OpenTelemetry Gradle Plugin](https://github.com/craigatk/opentelemetry-gradle-plugin) supports context propagation making sense of the `TRACEPARENT` and `TRACESTATE` environment variables.
Hopefully it's just documentation.

### Are you interested in contributing this feature?

Yes.
@craigatk would you be interested in this integration that may just be documentation?

**Comment by craigatk** [comment]
Sure, I'd be happy to update the OpenTelemetry Gradle plugin to more seamlessly integrate with the Jenkins OpenTelemetry plugin.

Currently the Gradle plugin looks for the parent trace ID and parent span ID with environment variables ([docs](https://github.com/craigatk/opentelemetry-gradle-plugin?tab=readme-ov-file#remote-parent-trace)), and I can add the specific environment variable names this Jenkins plugin uses.

For grabbing the parent trace ID and parent span ID in the Gradle plugin, is there documentation and/or code that lists what's in the TRACEPARENT and TRACESTATE environment variables published by the Jenkins plugin?

**Comment by craigatk** [comment]
Ahh I think I found it in the docs, looks like the Jenkins plugin is already exporting the same TRACE_ID and SPAN_ID environment variables that the Gradle plugin is looking for https://github.com/jenkinsci/opentelemetry-plugin/blob/main/docs/job-traces.md#environment-variables-for-trace-context-propagation-and-integrations

So this may just be a documentation update, as you mentioned.

**Comment by cyrille-leclerc** [comment]
Thanks Craig!

**Comment by kuisathaverat** [comment]
[pytest-otel](https://pypi.org/project/pytest-otel/) also support it

**Comment by cyrille-leclerc** [comment]
Works out of the box
<img width="2560" alt="image" src="https://github.com/user-attachments/assets/32dbcb9d-1dab-4358-b99f-6b383b501366">
