### ISSUE TITLE
Generate AWS X-ray compatible trace IDs

### ISSUE THREAD

**Issue by hhtpcd** [jenkinsci/opentelemetry-plugin#853]
### What feature do you want to see added?

It would be very useful when using AWS X-Ray to have the plugin be able to generate X-Ray compatible trace IDs. The awsxrayexporter chokes when it encounters non-xray ids. I'm not aware of other ways to convert or process non-xray IDs in flight at the otel-collector.

```
`2024-05-24T10:14:53.225Z	debug	awsxrayexporter@v0.78.0/awsxray.go:114	Error translating span.	{"kind": "exporter", "data_type": "traces", "name": "awsxray", "error": "invalid xray traceid: b47fb1759d3adef02fac9043e6d0354b"}`
```

I appreciate that vendor specific support might not be desirable but AWS might be a large enough of a use case to be considered, I'm not aware of other vendors using their own ID formats.

### Upstream changes

The [AWS distribution for the Java agent](https://github.com/aws-observability/aws-otel-java-instrumentation) patches in support for generating X-ray IDs, I wonder if this could be a toggle based on a configuration option in the Jenkins plugin.
- https://github.com/aws-observability/aws-otel-java-instrumentation/blob/v1.32.0/awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsTracerCustomizerProvider.java
- [AWS Java Agent - how it works](https://github.com/aws-observability/aws-otel-java-instrumentation?tab=readme-ov-file#how-it-works)

**Comment by hhtpcd** [comment]
I think I've found the answer, X-Ray started supporting W3C trace IDs ~8 months ago so no need to generate X-Ray format at the source. ADOT Collector >= v0.34 is required.

- https://aws.amazon.com/about-aws/whats-new/2023/10/aws-x-ray-w3c-format-trace-ids-distributed-tracing/

**Comment by cyrille-leclerc** [comment]
Thanks @hhtpcd . Can we then close this issue?

**Comment by hhtpcd** [comment]
Sure can - I've tested the plugin with the ADOT Collector and it works like a charm. Thanks for the plugin! ❤️
