### ISSUE TITLE
We are not able to send Jenkins Logs on New Relic using this plugin on Jenkins server

### ISSUE THREAD

**Issue by Akp-108** [jenkinsci/opentelemetry-plugin#860]
### What feature do you want to see added?

We want to send the Jenkins Build logs to the New lic but we are not able to send the logs there. Using this plugin Jenkins is sending only some logs on New Relic that are too low it is in the count of 6,7. We want to send all logs that are present in the Jenkins pipeline.
![image](https://github.com/jenkinsci/opentelemetry-plugin/assets/70027847/0c8a930f-840f-493a-a4ed-eaa02b20e8c8)

only this many logs we are getting on new relic through Jenkins.

### Are you interested in contributing this feature?

yes

**Comment by kuisathaverat** [comment]
I am not sure I understand the issue. 

* Is it a feature request? 
* Is it an issue? 
* Is it related to build logs? 
* Is it related to Jenkins logs? 
* What version of Jenkins are you using? 
* What version of the plugin are you using?
