### ISSUE TITLE
Customise the service name to support CI at Scale

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#88]
### What

Currently the service name is hardcoded with the `jenkins` service name

See https://github.com/jenkinsci/opentelemetry-plugin/blob/390ad7d1c156dff037219a018c99cd65a949e71b/src/main/java/io/jenkins/plugins/opentelemetry/opentelemetry/resource/JenkinsResourceProvider.java#L33-L38 and https://github.com/jenkinsci/opentelemetry-plugin/blob/b355859fa093dc5da00a1639d5d11d0d84427b2f/src/main/java/io/jenkins/plugins/opentelemetry/semconv/JenkinsOtelSemanticAttributes.java#L79-L87

Let's support a customise option when configuring the OpenTelemetry to set what's the service name to be used.

### Why

Several Jenkins coordinators to report to the same obs11 backend might clash if they have the same Jobs for any reason.

#### Given the Jenkins URL then calculate the service name

Given the Jenkins URL `https://foo.domain.com` then creates the service name: `foo.domain.com`

**Pros:**
- Delegate the responsability to the plugin to decide the name based on the Jenkins URL.

**Cons:**
- If JenkinsURL is too verbose (IP address, k8s namespaces...) then  it might be less user friendly.
- No customisation.

#### Provide a global settings to override the service name

Given a Global Settings called serviceName, with default value `Jenkins`, then update the service name.

**Pros:**
- User friendly
- More customisation.

**Cons:**
- Service name might not match with the Jenkins URL.

**Comment by skundrik** [comment]
What about having multiple options?

1. Manually specified, defaulting to "jenkins" as is now
2. Dynamic based on URL using something like grok to extract parts you want and combine them into service name

**Comment by v1v** [comment]
thanks @skundrik for the feedback.

 for 1) I've got something in place, see https://github.com/jenkinsci/opentelemetry-plugin/pull/97

 for the 2), would you mind if I ask you to elaborate a bit more how you foresee it?

Thanks
