### ISSUE TITLE
Add additional metrics for Garbage Collection and Memory stats

### ISSUE THREAD

**Issue by 1davidmichael** [jenkinsci/opentelemetry-plugin#883]
### What feature do you want to see added?

Currently some metrics that might be possible to collect, including for Garbage Collection and Memory utilization are not included. It would be nice if these could be included.

It looks like it should be possible to get these via the JVM metrics via JMX.

Here is an example from Elastic APM showing the missing metrics:
![image](https://github.com/jenkinsci/opentelemetry-plugin/assets/701900/18778257-b5a9-427d-84ed-095811ca1ac3)

**Comment by cyrille-leclerc** [comment]
Thanks for using the plugin @1davidmichael .
Do you mean that the Elastic APM panels "System memory usage", "Garbage Collection per minute", and "Garbage Collection time spent per minute"?

Can you please tell us what metric is Elastic APM looking for? Metric name and attributes?

**Comment by cyrille-leclerc** [comment]
Adding System CPU metrics with 
* https://github.com/jenkinsci/opentelemetry-plugin/pull/885

GC metrics should already be added

**Comment by kuisathaverat** [comment]
BTW JVM metrics have changed the fields path in the latest instrumentation version 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0
