### ISSUE TITLE
Capability to manually add attributes to spans

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkinsci/opentelemetry-plugin#91]
# Problem description

I want to manually add attributes to spans in my pipeline, similar to manually adding attributes to spans when instrumenting applications with distributed tracing.

Example use cases

* Add informations on shell steps to indicate the purpose of the shell step (e.g. an `sh 'docker login -u $user -p $pass my.docker.registry'`)
    * ❓ How to add attributes to atomic built-in steps ("non wrapping steps") like the `sh` step?

Exemple with the OpenTelemetry APIs for Java

```
Span currentSpan = Span.current();
currentSpan.setAttribute(""net.peer.name", "my.docker.registry");
currentSpan.setAttribute(""rpc.service", "docker");
currentSpan.setAttribute(""rpc.method", "login");
```

# See other problem statements

* [Capability to manually create spans #90](https://github.com/jenkinsci/opentelemetry-plugin/issues/90)
* [Capability to add "logs" to spans #92](https://github.com/jenkinsci/opentelemetry-plugin/issues/92)

# Proposed solutions

## `addAttributes()` pipeline step

TODO

## adding an `attributes` attribute to the built-in steps

TODO

**Comment by kuisathaverat** [comment]
I think this is already supported by using these steps:

* withSpanAttribute(key, value[, type][, target])
* setSpanAttributes([spanAttribute(key, value[, type][, target])])
* withSpanAttributes([spanAttribute(key, value[, type][, target])])
*
