### ISSUE TITLE
Add the ability to set status or record exception to a Span

### ISSUE THREAD

**Issue by roeycarmi** [jenkinsci/opentelemetry-plugin#928]
### What feature do you want to see added?

In java, i can do the following:
``` java
try {
    // Code that might throw an exception
} catch (Exception e) {
    span.recordException(e);
    span.setStatus(StatusCode.ERROR, "Exception occurred");
}
```
But the plugin function (i.e `setSpanAttributes`, `withSpanAttribute`, `withSpanAttributes`) only allow me to set attributes.

**Comment by kuisathaverat** [comment]
🤔 Can you give more details about the use case for this?

**Comment by roeycarmi** [comment]
I am running a python script that may return a variaty of exit codes.
In the groovy code I would like to decide for each return code whether to mark the span with status OK or ERROR.
Plus, I may want to put my own Exception message.
For example: my python script may return code 2 and I'll want to set the status to ERROR and record an exception "InfrastructureException Occured"

**Comment by kuisathaverat** [comment]
I think you can achieve that with something like this, to playing with [try-catch](https://www.jenkins.io/doc/book/pipeline/syntax/#flow-control) or [catcherror](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#catcherror-catch-error-and-set-build-result-to-failure) blocks in groovy, or even better using [post stages](https://www.jenkins.io/doc/book/pipeline/syntax/#post).

```groovy
script {
      ret = sh(script: 'exit $(echo "$RANDOM%4" |bc)', returnStatus: true)
      if(ret == 1){
         error("Error 1")
      } else if (ret == 2){
         error("Error 2")
      } else if (ret == 3){
         error("Error 3")
      } else if (ret == 4){
         error("Error 4")
      } else {
         error("Error unknow")
      }
}
```

**Comment by roeycarmi** [comment]
Great answer, thanks for the response!
