### ISSUE TITLE
Injecting span attributes to child spans at server level

### ISSUE THREAD

**Issue by rangamani54** [jenkinsci/opentelemetry-plugin#939]
### What feature do you want to see added?

I want to inject custom span attributes into the child spans, I can see `withSpanAttributes`, that it's working very well, but this will only work at the **job/pipeline level or stage level**. However, I need the custom span attributes on all pipelines running on the server. Can we have a **global configuration at the server level to inject/define custom span attributes**?

**Comment by cyrille-leclerc** [comment]
> global configuration at the server level to inject/define custom span attributes

Could you rely on resource attributes? If so, you just have to use config property `otel.resource.attributes`.

**Comment by kuisathaverat** [comment]
As Cyrille said you can use `otel.resources.attributes` or OTEL_RESOURCE_ATTRIBUTES environment variable passed to your Jenkins process.

https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/
